language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libspatialindex-dev
install:
  - pip install cffi BTrees==4.8.0 Rtree==0.9.7 Whoosh==2.7.4
script:
  - pytest -v
