language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libspatialindex-dev
install:
  - pip install cffi BTrees==4.10.0 Rtree==1.0.0 Whoosh==2.7.4
script:
  - pytest -v
